codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 5
  round: down
  range: 50...75
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        only_pulls: false
        branches: null
        flags: null
        paths: null

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - **/*Test.*
  - src/main/java/fr/polytech/projectjava/checkingsimulation/*.*
  - src/main/java/fr/polytech/projectjava/checkingsimulation/**/*.*
  - src/main/java/fr/polytech/projectjava/mainapp/jfx/*.*
  - src/main/java/fr/polytech/projectjava/mainapp/jfx/**/*.*
  - src/main/java/fr/polytech/projectjava/mainapp/socket/*.*
  - src/main/java/fr/polytech/projectjava/mainapp/Main.java
  - src/main/java/fr/polytech/projectjava/utils/*.*
  - src/main/java/fr/polytech/projectjava/utils/**/*.*
