language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
script: mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
notifications:
  email: false
  on_failure: always
  on_success: always
  slack:
    secure: az4j9OWzXgDcdSgxNoWbejCygGyz7Rtay/HoLywgvp5hD4WrXO+0SDz4pOi1CBw1rydzcXBMihyJrOK71JlptsITvgcU2gFUDaWRx3K3agvBA5jUXfwWDxJAST9v6S/aBPlb0TFR8SvjpAMDl/LMGq8KGZv0JBWw8FSd3NlpZav9dCOLPnBPT4beyA6sgYFh15QnrWgMNx7HxUMDNfgv0kuS3Y6y2cCbiTNKPTiEweeewaNzCyeIFvo0eKJOp8gGGKQEoQ3yOfEEWqrDc8JphHLOc5P8E2mnJdcYQZzGRVSanjuCuhYYh+l2z6/LFDxYKoOL8wtKrtL0AXVktXeBCVawkJlxGwtvRbJIiRsOkzrNkFUDkN7FXswmCEcM9v7y9ZfpF/MoRZKq7pXhnDP//ws6SgeovsCTMo0xvbZ1utNnDSWya1u46oZGwOfQEa2SuTt5w5SbVuHN7NAUD9miLSCcaQL6olcKr9uW8q11hyzXENtpQ9E4tcufmtRrCmh6PzDa+LaQfvjj5p90vgwIFuu4hbqa5OwBY0m2PhTogTfYi53AgybxUWaH2LoYfEp3X8WB6f0B0jhUw94dAsFntxnZ1GjkwDLpLdao+3zs1dmdJ7deE3uk8j7GbUWkI/ko2LSaibhvK9kLzbB/hXvannHwx0Y9Wj5gh8dyC4bsbKk=
env:
  global:
  - secure: zAFAk1mMV5aR8EJLpMddYC5b4l1wWQY6ahxfV1FR5ji0nwz/W2sEUbS68IXRnE0LRlEnqEMdMF9KcJFvHvx3Oprd6D7VU0/yNhCf4SG5SqeMtwJU/GaNcNTspW9VgIY4QdMnC3EG9F9ZuiINF+UEIE6azIgS4NS4juR3tadZ1JdITGGwazqI2jZUFcNPnUNsLh51KVdEW2s0Xnv6VrvOJTpIqGjVxrrDy9WbVwqdRXHmullYzsx5Dc4proosxpnyH7XLQeXBlTj3GZ54cSWDKuh3GvotgH8L0Xx7LmP1T7KZCGXuUw7rSBb30HVNg6TEaGneVA+dOVK9RUvomk/BFKjLcK0sKmuiCYQ1VKiW24s46+TKA14BBYhJ+0/m7zO+1bE0+ZVLWuafKN4B4YEkAZcTMYWn0gxIclKXVE/YqdA8WqccrSeHTmLRlhB2beO5jEgw59CDOxhQwoGQzp+4sw1zb2gT6mXdJzj+16sN7BMJx7RHGnBSaGEpRstNDA0MzHTiXjnOaxcyVcYJ7s4q9KAhfla5V277lDLtzO2lvJlpGqiYhdSnlVV2A0aggBhXNjEpOJbMq1RywIcMFql0Be9gjm0JfT4z/zc52txLUJ8wtnxCXPgAtsy+kKtHyOmD+fbtcCqJWWWubW5xeV7IbtTaNWO1gX22+ctPGAxT+aU=
  - secure: Rzm5FqNdjx/oJEsR2/gKtj3rfuxCKrVI3A1HriDRAWL91XISNyV6C1ZDKInCU3fzvHsFyxKgFFj84/Gob2Pws9/0av0THEP4B4Ukn0pc0gs8VAQbgc742pNxRB/La5IbnatXXZHdcKhb6MkLqDXgrUgGgzuY1HAbRNE/7x9ZVX8VLvMZ3+xCp1c4stzXpj5BCh4UWag6KfEQA1Cu0JiEyg9cD+fwN0A8epBp3TKgA7cxQOE6qmG1ZANMfPmjw3QcRsEs6qeepTaIA5BJ9d2IuYARtbgUs38Wgex/Rxhf7T5/X7dp3mOASFySnuQozOsWye7YnlE9UhUBqoenlwiQVrJbz6cjSYSyqbjvZFMQl/kvM/MgXqBxnHbR3DwErbc/eOHgDU9ZxfdVzV7IlqM447rSAiOgX9kKOW3a6dtJYh82L4Nw0w01RKiXhbmP93W/1Rf17D2t3qwX87CD64+9F8kahDhLn23ZpE6zyUjL4AaR7JScWBRrYyi0WUKQD9MGjaIlP10q4UDHWSosGYmwhpRol/9fIMeivWkqx5a9+rqIW53k+UpRsCR81sqKyUhY1mp1AoSW8cg5IyeZ9kxiiSK/I4GKiMGCefyw374LJfk4TIWAT/ocA7F+0lcFtILSGvqT1TOHk/wvg7egXRWdSYpXsp2xM9esIiBVkf2k2BI=
